name: Insert Metadata

on:
  pull_request:
    types: [opened]
    paths:
      - 'your-specific-folder/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Get PR info and modify file
      run: |
           PR_ID=${{ github.event.pull_request._links.self.href }}
           PR_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PR_ID/files)
           FILE=$(echo $PR_JSON | jq -r '.[0] .filename')

           if [[ $FILE =~ ^your-specific-folder/ ]]; then
             echo "Inserting metadata to $FILE"
             echo "metadata here" >> $FILE

             git config --global user.email "action@github.com"
             git config --global user.name "GitHub Action"
             git add $FILE
             git commit -m "Update $FILE with metadata"
             git push
           else
             echo "$FILE is not part of your-specific-folder, skipping..."
           fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
